swagger: '2.0'
info:
  version: '1.0.0'
  title: Fuseml
  description: FuseML service API
schemes:
  - http
host: localhost
basePath: /api
consumes: 
  - application/json
produces: 
  - application/json
paths:
  /runnables:
    get:
      summary: Retrieve runnable information
      description: Get information about runnables currently registered in the FuseML runnable store
      tags:
        - runnable
      operationId: listRunnables
      parameters:
        - name: id
          in: query
          description: The runnable's id
          required: false
          type: string
      responses:
        200:
          description: Return all registered runnables matching the query
          schema:
            type: array
            items:
              $ref: '#/definitions/Runnable'
    post:
      summary: Register runnable
      description: Register a runnable with the FuseML runnable store
      tags:
        - runnable
      operationId: registerRunnable
      parameters:
        - name: runnable
          in: body
          description: Runnable descriptor
          required: true
          schema:
            $ref: '#/definitions/RunnableReq'
      responses:
        201:
          description: Runnable registered
          schema:
            $ref: '#/definitions/Runnable'
        400:
          description: Bad Request
  /runnables/{runnableNameOrId}:
    get:
      summary: Get information about a runnable
      description: Lookup information about a runnable in the FuseML store
      tags:
        - runnable
      operationId: getRunnable
      parameters:
        - name: runnableNameOrId
          in: path
          description: Runnable name or id
          required: true
          type: string
      responses:
        200:
          description: Return matching runnable resource
          schema:
            $ref: '#/definitions/Runnable'
        400:
          description: Bad Request
        404:
          description: Runnable Not Found

definitions:
  RunnableReq:
    type: object
    properties:
      name:
        type: string
        description: The name of the runnable
      kind:
        type: string
        description: The kind of runnable (builder, trainer, predictor etc.)
      image:
        $ref: '#/definitions/RunnableImage'
        description: The OCI container image associated with the runnable
      inputs:
        type: array
        items:
          $ref: '#/definitions/RunnableInput'
        description: List of inputs (artifacts, values etc.) accepted by this runnable
      outputs:
        type: array
        items:
          $ref: '#/definitions/RunnableOutput'
        description: List of outputs (artifacts, values etc.) generated by this runnable
      labels:
        type: array
        description: Labels associated with the runnable
        items:
          type: string
  Runnable:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: The ID of the runnable
      name:
        type: string
        description: The name of the runnable
      kind:
        type: string
        description: The kind of runnable (builder, trainer, predictor etc.)
      image:
        $ref: '#/definitions/RunnableImage'
        description: The OCI container image associated with the runnable
      inputs:
        type: array
        items:
          $ref: '#/definitions/RunnableInput'
        description: List of inputs (artifacts, values etc.) accepted by this runnable
      outputs:
        type: array
        items:
          $ref: '#/definitions/RunnableOutput'
        description: List of outputs (artifacts, values etc.) generated by this runnable
      created:
        type: string
        format: date-time
        description: The runnable's creation time
      labels:
        type: array
        description: Labels associated with the runnable
        items:
          type: string
  RunnableImage:
    type: object
    properties:
      registryUrl:
        type: string
        description: The URL for the external registry where the image is stored (empty for internal images)
      repository:
        type: string
        description: The image repository
      tag:
        type: string
        description: The image tag
  RunnableInput:
    type: object
    properties:
      name:
        type: string
        description: Input name
      kind:
        type: string
        description: Kind of input (e.g. runnable, dataset, model, parameter etc.)
      runnable:
        $ref: '#/definitions/RunnableRef'
        description: Runnable reference 
      parameter:
        $ref: '#/definitions/InputParameter'
        description: Parameter description 
  RunnableRef:
    type: object
    properties:
      name:
        type: string
        description: Runnable name
      kind:
        type: string
        description: Runnable kind
      labels:
        type: array
        description: Runnable labels 
        items:
          type: string          
  InputParameter:
    type: object
    properties:
      datatype:
        type: string
        description: Parameter data type
      optional:
        type: boolean
        default: true
        description: Optional parameter
      default:
        type: string
        description: Default value 
  RunnableOutput:
    type: object
    properties:
      name:
        type: string
        description: Input name
      kind:
        type: string
        description: Kind of input (e.g. runnable, dataset, model, metadata etc.)
      runnable:
        $ref: '#/definitions/RunnableRef'
        description: Runnable reference 
      metadata:
        $ref: '#/definitions/InputParameter'
        description: Metadata description 
